# Generated by Django 3.2.4 on 2021-06-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_alter_show_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(),
        ),
    ]
