# Generated by Django 3.2.4 on 2021-06-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_alter_show_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
