# Generated by Django 3.2.4 on 2021-06-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_alter_show_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(error_messages={'show_title_dupe': 'Title musy be unique.'}, max_length=255, unique=True),
        ),
    ]
